# Use the official PostgreSQL image from the Docker Hub
FROM postgres:13

# Set environment variables for the PostgreSQL database
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_DB=EJawTestCase
ENV POSTGRES_DRIVER = postgres
ENV POSTGRES_PORT=5432
ENV POSTGRES_HOST=db

# Expose the PostgreSQL port
EXPOSE 5432